import debug from 'debug';

import type { App } from '../App.js';
import { prepareClientAppEnhances } from './prepare/prepareClientAppEnhances.js';
import { prepareClientAppRootComponents } from './prepare/prepareClientAppRootComponents.js';
import { prepareClientAppSetups } from './prepare/prepareClientAppSetups.js';
import { prepareLayoutComponents } from './prepare/prepareLayoutComponents.js';
import { preparePageComponent } from './prepare/preparePageComponent.js';
import { preparePageData } from './prepare/preparePageData.js';
import { preparePagesComponents } from './prepare/preparePagesComponents.js';
import { preparePagesData } from './prepare/preparePagesData.js';
import { preparePagesRoutes } from './prepare/preparePagesRoutes.js';
import { prepareSiteData } from './prepare/prepareSiteData.js';

const log = debug('vitebook:core/app');

/**
 * Prepare files for development or build.
 *
 * - page components
 * - routes
 * - site data
 * - other files that are generated by plugins
 */
export const prepareApp = async (app: App): Promise<void> => {
  log('prepare start');

  await app.pluginManager.hooks.beforePrepare.process(app);

  // generate page component files
  for (const page of app.pages) {
    await preparePageComponent(app, page);
  }

  await preparePagesComponents(app);

  // generate page data files
  for (const page of app.pages) {
    await preparePageData(app, page);
  }
  await preparePagesData(app);

  // generate routes file
  await preparePagesRoutes(app);

  // generate layout components map file
  await prepareLayoutComponents(app);

  // generate site data file
  await prepareSiteData(app);

  // generate client app enhances file
  await prepareClientAppEnhances(app);

  // generate client app root components file
  await prepareClientAppRootComponents(app);

  // generate client app setups file
  await prepareClientAppSetups(app);

  await app.pluginManager.hooks.afterPrepare.process(app);

  log('prepare finish');
};
